#!/bin/bash

mkdir -p working
ARFFRTE=working/rte.arff
RUN=working/sick.run
SICK=working/sick

createrun()
{
    echo -e "pair_ID\tentailment_judgment\trelatedness_score" > ${RUN}
    for I in `ls ${SICK}`; do
	echo -n -e "${I}\t" >> ${RUN}
	if [ -f ${SICK}/${I}/modsizedif.txt ]; then
	    DSD=`cat ${SICK}/${I}/modsizedif.txt | grep domain | cut -d" " -f1 | sed 's/.$//'`
	    RSD=`cat ${SICK}/${I}/modsizedif.txt | grep relation | cut -d" " -f1 | sed 's/.$//'`
	    WND=`cat ${SICK}/${I}/modsizedif.txt | grep wordnet | cut -d" " -f1 | sed 's/.$//'`
	    OVE=`cat ${SICK}/${I}/modsizedif.txt | grep overlap | cut -d" " -f1 | sed 's/.$//'`
	    RTE=`cat ${SICK}/${I}/prediction.txt | cut -d"." -f1`
	    if [ `echo ${RTE} | grep proof | wc -l` -gt 0 ]; then
		SIM=`echo "3 k -1.8889 ${DSD} * 1.8838 ${RSD} * -0.2259 ${OVE} * 4.8972 + + + p" | sed 's/-/_/g' | dc`
		echo -n -e "ENTAILMENT\t" >> ${RUN}
		echo "${SIM}" >> ${RUN}
	    elif [ `echo ${RTE} | grep inconsisten | wc -l` -gt 0 ]; then
		SIM=`echo "3 k 0.3875 ${OVE} * 3.3122 + p" | sed 's/-/_/g' | dc`
		echo -n -e "CONTRADICTION\t" >> ${RUN}
		echo "${SIM}" >> ${RUN}
	    else
		SIM=`echo "3 k 0.2753 ${RSD} * 0.6857 ${WND} * 1.5522 ${OVE} * 1.8168 + + + p" | sed 's/-/_/g' | dc`	      
	      	echo -n -e "NEUTRAL\t" >> ${RUN}
		echo "${SIM}" >> ${RUN}
	    fi
	else
	    echo -n -e "NEUTRAL\t" >> ${RUN}
	    echo "4" >> ${RUN}
	fi	
    done
}

arffsim()
{
    ARFFSIM=working/sim$1.arff
    echo "@RELATION sim$1" > ${ARFFSIM}
    echo "" >> ${ARFFSIM}
    echo "@ATTRIBUTE domsizedif NUMERIC"  >> ${ARFFSIM}
    echo "@ATTRIBUTE relsizedif NUMERIC"  >> ${ARFFSIM}
    echo "@ATTRIBUTE wordnetdif NUMERIC"  >> ${ARFFSIM}
    echo "@ATTRIBUTE wordoverlap NUMERIC" >> ${ARFFSIM}
    echo "@ATTRIBUTE similarity NUMERIC"  >> ${ARFFSIM}
    echo "" >> ${ARFFSIM}
    echo "@DATA" >> ${ARFFSIM}
    for I in `ls ${SICK}`; do
	case $1 in 
	    ENTAILMENT)
		if [ `cat ${SICK}/${I}/prediction.txt | grep proof | wc -l` -gt 0 ]; then
		    if [ -f ${SICK}/${I}/modsizedif.txt ]; then
			DSD=`cat ${SICK}/${I}/modsizedif.txt | grep domain | cut -d" " -f1 | sed 's/.$//'`
			RSD=`cat ${SICK}/${I}/modsizedif.txt | grep relation | cut -d" " -f1 | sed 's/.$//'`
			WND=`cat ${SICK}/${I}/modsizedif.txt | grep wordnet | cut -d" " -f1 | sed 's/.$//'`
			OVE=`cat ${SICK}/${I}/modsizedif.txt | grep overlap | cut -d" " -f1 | sed 's/.$//'`
			SIM=`cat ${SICK}/${I}/gold.sim`
			echo "${DSD},${RSD},${WND},${OVE},${SIM}" >> ${ARFFSIM}
		    fi	
		fi;;
	    CONTRADICTION)
		if [ `cat ${SICK}/${I}/prediction.txt | grep inconsis | wc -l` -gt 0 ]; then
		    if [ -f ${SICK}/${I}/modsizedif.txt ]; then
			DSD=`cat ${SICK}/${I}/modsizedif.txt | grep domain | cut -d" " -f1 | sed 's/.$//'`
			RSD=`cat ${SICK}/${I}/modsizedif.txt | grep relation | cut -d" " -f1 | sed 's/.$//'`
			WND=`cat ${SICK}/${I}/modsizedif.txt | grep wordnet | cut -d" " -f1 | sed 's/.$//'`
			OVE=`cat ${SICK}/${I}/modsizedif.txt | grep overlap | cut -d" " -f1 | sed 's/.$//'`
			SIM=`cat ${SICK}/${I}/gold.sim`
			echo "${DSD},${RSD},${WND},${OVE},${SIM}" >> ${ARFFSIM}
		    fi	
		fi;;
	    NEUTRAL)
		if [ `cat ${SICK}/${I}/prediction.txt | grep word | wc -l` -gt 0 ]; then
		    if [ -f ${SICK}/${I}/modsizedif.txt ]; then
			DSD=`cat ${SICK}/${I}/modsizedif.txt | grep domain | cut -d" " -f1 | sed 's/.$//'`
			RSD=`cat ${SICK}/${I}/modsizedif.txt | grep relation | cut -d" " -f1 | sed 's/.$//'`
			WND=`cat ${SICK}/${I}/modsizedif.txt | grep wordnet | cut -d" " -f1 | sed 's/.$//'`
			OVE=`cat ${SICK}/${I}/modsizedif.txt | grep overlap | cut -d" " -f1 | sed 's/.$//'`
			SIM=`cat ${SICK}/${I}/gold.sim`
			echo "${DSD},${RSD},${WND},${OVE},${SIM}" >> ${ARFFSIM}
		    fi	
		fi;;
	esac
    done
}

arffrte()
{
    echo "@RELATION rte" > ${ARFFRTE}
    echo "" >> ${ARFFRTE}
    echo "@ATTRIBUTE wordoverlap NUMERIC" >> ${ARFFRTE}
    echo "@ATTRIBUTE entailment {NEUTRAL,ENTAILMENT,CONTRADICTION}" >> ${ARFFRTE}
    echo "" >> ${ARFFRTE}
    echo "@DATA" >> ${ARFFRTE}
    for I in `ls ${SICK}`; do
	if [ -f ${SICK}/${I}/modsizedif.txt ]; then
	    OVE=`cat ${SICK}/${I}/modsizedif.txt | grep overlap | cut -d" " -f1 | sed 's/.$//'`
	    RTE=`cat ${SICK}/${I}/gold.rte`
	    echo "${OVE},${RTE}" >> ${ARFFRTE}
	fi	
    done
}



#arffrte

arffsim ENTAILMENT
arffsim CONTRADICTION
arffsim NEUTRAL

createrun
R --no-save --slave --vanilla --args ${RUN} working/SICK_all.txt < working/sick_evaluation.R 
